version: '3.7'

x-all:
  &all
  build: .
  restart: always
  env_file:
    - .env
  networks:
    - tg_bot

services:
  bot:
    <<: *all
    command: python3 -m bot
  #  web:
  #    restart: always
  #    build:
  #      context: .
  #      dockerfile: Front.Dockerfile
  #    ports:
  #      - "3000:3000"
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.tori.rule=Host(`tori.vdmax.ga`)"
  #      - "traefik.http.routers.tori.entrypoints=https"
  server:
    <<: *all
    command: python3 -m API
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
    restart: always
    networks:
      - tg_bot
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - tg_bot
networks:
  tg_bot:
    driver: bridge
